### ISSUE TITLE
buffer size

### ISSUE THREAD

**Issue by fernandex00** [dgtaheno/artillery-Genius#11]
im having issues with octoprint and the solution is changing the buffer size in marlin configuration, this two values
BLOCK_BUFFER_SIZE from 16 to 32
TX_BUFFER_SIZE from 0 to 32

do you think is posible?

**Comment by dgtaheno** [comment]
Hello @fernandex00 ,

Thank you for your feedback and my apologies for coming back to you that late, I have been quite busy lately.

I made the modification you suggested in the firmware and the new test firmware is:

https://github.com/dgtaheno/artillery-Genius-Marlinfw/blob/Marlin-2.1.2/Marlin%202.1.2_BufferFix.hex

I´d appreciate if you could test it and if it works I will apply this change in the main firmware permanently.

Best regards.

**Comment by fernandex00** [comment]
thank you, i will test it!

**Comment by fernandex00** [comment]
hi im having trouble updating the firmware, i dont know if this is causing by the firmware itself, already turn on the conection and chek my usb cable but i get thi error. "could not open port and can't open device "\\.\COM5

**Comment by dgtaheno** [comment]
> hi im having trouble updating the firmware, i dont know if this is causing by the firmware itself, already turn on the conection and chek my usb cable but i get thi error. "could not open port and can't open device "\\.\COM5

Hello,
I just experienced the same problem once I have the new TFT firmware, the problem is that Marlin baud rate is set now at 250000, but prisa slicer and others are configured to 115200 for the communication.

Solution:
Before connecting the printer via usb to the computer it is required to:
Menu->Settings->connection->S.ports there change 1.Printer parameter from 250000 to 115200 and go back to Connection menu and click ON and after that disconnect.

There you can upload the new firmware.

After it is done updating the firmware, come back click back on OFF in connection and set the baudrate again to 250000 otherwise the motherboard will not connect to the tft.

And with that you should be done.

If you need further assistance don't hesitate to reach out.

Best regards.

**Comment by fjherna** [comment]
Hi All,
[NOTE TO ALL: I am really sorry that my first post was in Spanish (my mother-language). :( ]

Hi all and in particularly to dgtaheno,

Sorry for approaching you like this without having participated before. I have seen a project on GitHub, in which I am very interested and I think it is related to this forum.

I have an Artillery Genius (basic and one of the first since I have had it for a few years now; I seem to remember it was in January 2021).

I admit that I have quite abandoned it, and just now I have decided to take it up again.

I'll give you a little background on what my current situation is. I'm totally new to 3D printing and have only made a few pieces of my own, apart from printing some from thingiverse.
:)
The most I have done is install Marlin 2.0.5.3 and then compile the current Marlin 2.1.x myself to update it, so I changed the original extruder for a "Trianglelab MATRIX" one (similar to the HEMERA, but cheaper).

A few days ago I considered looking for a complementary screen to manage the printer and the Firmware a little better if possible.

In my search I found some interesting information on YouTube (https://www.youtube.com/watch?v=H3mHDbtcaxU). I then thought about purchasing a FYSETC screen, but the problem is that in that article it only mentions Marlin 1.9.0 and 2.0.5.3. Furthermore, it is from three years ago and is currently not active. I asked about the possibility of using a Marlin 2.1.x with those FYSETC or similar screens, but I don't expect anyone to answer.

In view of this, I continued searching and yesterday I found your project in which Firmware 2.1.2.1 is mentioned and some BigtreeTech TFT Touchscreen screens that seemed to me could have possibilities with my Artillery Genius.
In the links I have seen (https://github.com/dgtaheno/artillery-Genius-Genius_Pro-X1-Marlinfw) the project is quite recent.

Well, I don't want to go into more detail (perhaps it's already too much and I'm sorry), because my intention was only to make contact with you regarding this project, and to find out if it is still going.

Of course I offer to collaborate in whatever is necessary, always considering the modest measure of my possibilities and limitations.

Everyone receive a cordial greeting,

fjherna1

---------------------------------[Spanish version]-------------------------------------------------
Hola a todos y particularmente a dgtaheno,

Disculpen que les aborde así sin haber participado antes. He visto un proyecto que hay en GitHub, en el que estoy muy interesado y creo que esta relacionado con este foro.

Tengo una Artillery Genius (básica y de las primeras pues ya hace unos cuantos años que la tengo; creo recordar que fue en Enero 2021).

Reconozco que la tengo bastante abandonada, y justo ahora me he decidido a retomarla.

Les pongo un poco en antecedentes de cual es mi situación actual. Soy totalmente nuevo con la impresion 3D y apenas he hecho unas pocas piezas propias, además de imprimir algunas de thingiverse.
🙂
Lo mas que he hecho ha sido instalar el Marlin 2.0.5.3 y posteriormente compilar yo mismo el Marlin 2.1.x actual para actualizarlo, pues cambie el extrusor original por uno "Trianglelab MATRIX" (del estilo del HEMERA, pero mas barato).

Hace unos días que me plantee buscar una pantalla complementaria para manejar un poco mejor la impresora y el Firmware si fuera posible. 

En mi búsqueda encontré una información interesante en YouTube (https://www.youtube.com/watch?v=H3mHDbtcaxU). Pensé entonces en adquirir una pantalla FYSETC, pero el problema es que en ese articulo menciona solamente Marlin 1.9.0 y 2.0.5.3 Además es de hace tres años y no tiene actualmente actividad. Pregunte por la posibilidad de usar un Marlin 2.1.x con esas pantallas FYSETC o similares, pero no espero que nadie conteste.

En vista de ello seguí buscando y fue como di ayer con su proyecto en el que se menciona un Firmware 2.1.2.1 y unas pantallas BigtreeTech TFT Touchscreen que me parecieron que podrían tener posibilidades con mi Artillery Genius.
En los enlaces que he visto (https://github.com/dgtaheno/artillery-Genius-Genius_Pro-X1-Marlinfw) el proyecto es bastante reciente.

Bueno no me quiero extender mas (quizas ya es demasiado y lo siento), pues mi intención era únicamente una toma de contacto con Vd. respecto a este proyecto, y saber si sigue en marcha.

Por supuesto que me ofrezco a colaborar en lo que hiciera falta, siempre considerando la modesta medida de mis posibilidades y limitaciones.

Reciban todos un cordial saludo,

fjherna1
